server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: alter
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}
apple:
  team_id: ${APPLE_TEAM_ID}
  login_key: ${APPLE_LOGIN_KEY}
  private_key: ${APPLE_PRIVATE_KEY}
  client_id: ${APPLE_CLIENT_ID}
  service_id: ${APPLE_SERVICE_ID}
  redirect_uri: ${APPLE_REDIRECT_URI}
jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token:
    expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
alter:
  security:
    allowed-origin-patterns: ${ALLOWED_ORIGIN_PATTERNS}
    allowed-methods: ${ALLOWED_METHODS}
    allowed-headers: ${ALLOWED_HEADERS}
    exposed-headers: ${EXPOSED_HEADERS}
    allowed-pattern: ${ALLOWED_PATTERN}
    permit-all-urls: ${PERMIT_ALL_URLS}
